// ==========================================
// NandiGen AI - Backend Server
// Developer: Nandipha Magalakangqa
// ==========================================

const express = require("express");

const app = express();

const PORT = process.env.PORT || 3000;


// ==========================================
// Middleware
// ==========================================

app.use(express.json());


// ==========================================
// Health Check
// ==========================================

app.get("/", (req, res) => {

    res.json({
        message: "NandiGen AI backend is running successfully!",
        project: "NandiGen AI - Intelligent Content Studio",
        developer: "Nandipha Magalakangqa"
    });

});


// ==========================================
// AI Content Generation
// ==========================================

app.post("/api/generate", async (req, res) => {

    try {

        const { prompt, contentType } = req.body;


        // Check that a prompt was provided
        if (!prompt) {

            return res.status(400).json({
                error: "Please provide a prompt."
            });

        }


        // Temporary response
        // This will be replaced with a real AI model later.

        const generatedContent = `
NandiGen AI Content Preview

Content Type:
${contentType || "General Content"}

Prompt:
${prompt}

This is a temporary AI response generated by
the NandiGen AI backend.

The next development stage will connect this
backend to a real AI model.
`;


        // Send response back to frontend

        res.json({
            success: true,
            content: generatedContent
        });


    } catch (error) {

        console.error("Server error:", error);

        res.status(500).json({
            success: false,
            error: "Unable to generate content."
        });

    }

});


// ==========================================
// Start Server
// ==========================================

app.listen(PORT, () => {

    console.log(
        `NandiGen AI server is running on port ${PORT}`
    );

});
